org.gradle.jvmargs=-Xms1G -Xmx3G
org.gradle.daemon=false

mod_id=arsccturret
mod_name=Ars CC Turret
package_group=com.yui.arsccturret
mod_version=1.0.0
mc_version=1.20.1
forge_version=47.2.0
ars_version=4.12.7.264
gecko_version=4.8.2
cct_version=1.111.0
# Ars Nouveau の実行時 mandatory 依存(runClient で Ars 実ロードに必要)
curios_version=5.11.1+1.20.1
mixin_extras_version=0.4.1
